version: '3'

volumes:
  postgresql.data:
  redis_session.data:

services:
   db:
    image: postgres:13
    container_name: postgres.docker
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ~/data/postgresql.data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${DATABASE_PORT}:5432
    networks:
      - global

  redis-session:
    image: redis:7
    container_name: redis.session.docker
    restart: unless-stopped
    environment:
      REDIS_PASS: ${REDIS_SESSION_PASS}
      REDIS_PORT: ${REDIS_SESSION_PORT}
    volumes:
      - redis_session.data:/data
    ports:
      - 127.0.0.1:${REDIS_SESSION_PORT}:6379
    networks:
      - global

  server:
    container_name: server
    build:
      context: server
      target: production
      dockerfile: Dockerfile
    networks:
      - global 
    restart: unless-stopped 

  frontend:
    container_name: frontend
    build:
      context: frontend
      target: production
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:${FRONTEND_PORT}:20118
    networks:
      - global
    restart: unless-stopped

networks:
  global:
    external: true
