version: '3'

volumes:
    postgresql.data:
    redis_session.data:

services:
    db:
        image: postgres:13
        container_name: postgres.docker
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ~/data/postgresql.data:/var/lib/postgresql/data
        ports:
            - 127.0.0.1:${POSTGRES_PORT}:5432
        networks:
            - global

    redis-session:
        image: redis:7
        container_name: redis.session.docker
        restart: unless-stopped
        environment:
            REDIS_PASS: ${REDIS_SESSION_PASS}
            REDIS_PORT: ${REDIS_SESSION_PORT}
        volumes:
            - redis_session.data:/data
        ports:
            - 127.0.0.1:${REDIS_SESSION_PORT}:6379
        networks:
            - global

networks:
    global:
        external: true
