volumes:
    libretranslate_models:
    postgresql.data:
    redis_session.data:

services:
    db:
        image: postgres:12
        container_name: postgres.docker
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_HOST=${DB_HOST}
            - POSTGRES_PORT=${DB_PORT}
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', '${DB_USER}']
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - 127.0.0.1:${DB_PORT}:5432
        volumes:
            - postgresql.data:/var/lib/postgresql/data
        networks:
            - global

    redis_session:
        image: redis:7
        container_name: redis.session.docker
        restart: unless-stopped
        command: redis-server --requirepass ${REDIS_SESSION_PASS}
        volumes:
            - redis_session.data:/data
        ports:
            - 127.0.0.1:${REDIS_SESSION_PORT}:6379
        networks:
            - global

    translator:
        image: libretranslate/libretranslate:v1.6.2
        container_name: translator.docker
        environment:
            - LT_LOAD_ONLY=pl,en
            - LT_UPDATE_MODELS=true
            - LT_PORT=${TRANSLATE_APP_PORT}
        restart: unless-stopped
        tty: true
        entrypoint: ["/bin/sh", "-c", "./venv/bin/python scripts/install_models.py --load_only_lang_codes 'pl,en' && ./venv/bin/libretranslate --host '*'"]
        ports:
            - 127.0.0.1:${TRANSLATE_APP_PORT}:5000
        volumes:
            # Keep the models in a docker volume, to avoid re-downloading on startup
            - libretranslate_models:/home/libretranslate/.local:rw
        networks:
            - global

networks:
    global:
