FROM postgres:14-alpine

ARG POSTGRES_PORT=5432
ARG POSTGRES_USER=postgres
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_PORT=${POSTGRES_PORT}

EXPOSE ${POSTGRES_PORT}

HEALTHCHECK CMD pg_isready -U "$POSTGRES_USER" || exit 1
